export { AmazonLogo } from "./amazon-logo";
export { VcApproach } from "./vc-approach";
export { VcChallenge } from "./vc-challenge";
export { VcCta } from "./vc-cta";
export { VC_FAQS, VcFaq } from "./vc-faq";
export { VcHero } from "./vc-hero";
export { VcIncluded } from "./vc-included";
export { VcPortfolio } from "./vc-portfolio";
export { VcProcess } from "./vc-process";
export { VcWhy } from "./vc-why";
